name: Compile TS

on:
  pull_request:
    types: [ opened ]
  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install npm packages
        run: npm ci

      - name: Compile project
        run: npm run compile

      - name: Test lint
        run: npm run lint